---
# This Playbook deploys the application code
#   js front-end and rest based services backend

- hosts: application_backend
  roles:
    - role: contra

- hosts: application_backend
  roles:
    -role: galaga

- hosts: application_frontend
  roles:
    -role: galaga-ui
