---
- hosts: dbservers
  sudo: yes

  tasks:
  - name: Create Mongo bin dir
    file: path=/usr/nano/bin state=directory

  - name: Create Mongo data dir
    file: path={{ mongo_data_dir }} mode=755 state=directory

  - name: Create Mongo log dir
    file: path={{ mongo_log_dir }} mode=755 state=directory

  - name: Install Mongod
    copy: src=/usr/nano/build/bin/mongod mode=744 dest=/usr/nano/bin/mongod

  - name: Install Mongo
    copy: src=/usr/nano/build/bin/mongo mode=755 dest=/usr/nano/bin/mongo

  - name: Install Mongodump
    copy: src=/usr/nano/build/bin/mongodump mode=755 dest=/usr/nano/bin/mongodump

  - name: Install Mongoexport
    copy: src=/usr/nano/build/bin/mongoexport mode=755 dest=/usr/nano/bin/mongoexport

  - name: Install Mongofiles
    copy: src=/usr/nano/build/bin/mongofiles mode=755 dest=/usr/nano/bin/mongofiles

  - name: Install Mongoimport
    copy: src=/usr/nano/build/bin/mongoimport mode=755 dest=/usr/nano/bin/mongoimport

  - name: Install Mongooplog
    copy: src=/usr/nano/build/bin/mongooplog mode=755 dest=/usr/nano/bin/mongooplog

  - name: Install Mongoperf
    copy: src=/usr/nano/build/bin/mongoperf mode=755 dest=/usr/nano/bin/mongoperf

  - name: Install Mongorestore
    copy: src=/usr/nano/build/bin/mongorestore mode=755 dest=/usr/nano/bin/mongorestore

  - name: Install Mongos
    copy: src=/usr/nano/build/bin/mongos mode=755 dest=/usr/nano/bin/mongos

  - name: Install Mongostat
    copy: src=/usr/nano/build/bin/mongostat mode=755 dest=/usr/nano/bin/mongostat

  - name: Install Mongotop
    copy: src=/usr/nano/build/bin/mongotop mode=755 dest=/usr/nano/bin/mongotop

  - name: Create Mongo data dir
    file: path={{ mongo_data_dir }} mode=755 state=directory

  - name: Create Mongo log dir
    file: path={{ mongo_log_dir }} mode=755 state=directory

  - name: Create Consul config
    template: src=templates/mongodb.conf dest=/etc/mongodb.conf

  - name: Install mongo init script
    copy: src=files/init.d/mongodb mode=744 dest=/etc/init.d/mongodb

  - name: Run chkconfig to enable service
    command: /sbin/chkconfig --set mongodb on

  - name: Enable mongod service
    command: /etc/init.d/mongodb start
