---
# This Playbook deploys the web server and administrative front-ends

- hosts: webservers
  roles:
    - role: apache

- hosts: kibana_ui
  roles:
    -role: kibana-ui

- hosts: consul_ui
  roles:
    -role: consul-ui

  handlers:
    -include: handlers/restart_apache.yml
