---
- hosts: application
  vars:
  sudo: yes

  tasks:
  - name: Create bin dir
    file: path=/usr/nano/go/bin mode=755 state=directory

  - name: Install Authentication
    copy: src=/usr/nano/build/go/bin/authentication mode=744 dest=/usr/nano/bin/authentication

  - name: Install Authorization
    copy: src=/usr/nano/build/go/bin/authorization mode=744 dest=/usr/nano/bin/authorization

  - name: Install Challenge
    copy: src=/usr/nano/build/go/bin/challenge mode=744 dest=/usr/nano/bin/challenge

  - name: Install Identity
    copy: src=/usr/nano/build/go/bin/identity mode=744 dest=/usr/nano/bin/identity

  - name: Install Security
    copy: src=/usr/nano/build/go/bin/security mode=744 dest=/usr/nano/bin/security

  - name: Create log directory
    file: path={{ aeb_log_dir }} state=directory

  - name: Create data dir
    file: path={{ aeb_data_dir }} mode=755 state=directory
